export const iso639 = {
  afr: {
    nativeName: 'Afrikaans',
    referenceName: 'Afrikaans',
    part1: 'af',
    part2t: 'afr',
    part2b: 'afr',
    part6: 'afrs',
  },
  sqi: {
    nativeName: 'Shqip',
    referenceName: 'Albanian',
    part1: 'sq',
    part2t: 'sqi',
    part2b: 'alb',
    part6: null,
  },
  amh: {
    nativeName: 'አማርኛ',
    referenceName: 'Amharic',
    part1: 'am',
    part2t: 'amh',
    part2b: 'amh',
    part6: null,
  },
  ara: {
    nativeName: 'العربية',
    referenceName: 'Arabic',
    part1: 'ar',
    part2t: 'ara',
    part2b: 'ara',
    part6: null,
  },
  hye: {
    nativeName: 'Հայերեն',
    referenceName: 'Armenian',
    part1: 'hy',
    part2t: 'hye',
    part2b: 'arm',
    part6: null,
  },
  asm: {
    nativeName: 'অসমীয়া',
    referenceName: 'Assamese',
    part1: 'as',
    part2t: 'asm',
    part2b: 'asm',
    part6: null,
  },
  aze: {
    nativeName: 'Azərbaycan',
    referenceName: 'Azerbaijani',
    part1: 'az',
    part2t: 'aze',
    part2b: 'aze',
    part6: null,
  },
  eus: {
    nativeName: 'euskara',
    nativeNameVariant: 'euskera',
    referenceName: 'Basque',
    part1: 'eu',
    part2t: 'eus',
    part2b: 'baq',
    part6: null,
  },
  bel: {
    nativeName: 'беларуская мова',
    referenceName: 'Belarusian',
    part1: 'be',
    part2t: 'bel',
    part2b: 'bel',
    part6: null,
  },
  ben: {
    nativeName: 'বাংলা',
    referenceName: 'Bengali',
    part1: 'bn',
    part2t: 'ben',
    part2b: 'ben',
    part6: null,
  },
  bos: {
    nativeName: 'bosanski jezik',
    referenceName: 'Bosnian',
    part1: 'bs',
    part2t: 'bos',
    part2b: 'bos',
    part6: 'boss',
  },
  bul: {
    nativeName: 'български език',
    referenceName: 'Bulgarian',
    part1: 'bg',
    part2t: 'bul',
    part2b: 'bul',
    part6: 'buls',
  },
  mya: {
    nativeName: 'ဗမာစာ',
    referenceName: 'Burmese',
    part1: 'my',
    part2t: 'mya',
    part2b: 'bur',
    part6: null,
  },
  cat: {
    nativeName: 'català',
    referenceName: 'Catalan',
    part1: 'ca',
    part2t: 'cat',
    part2b: 'cat',
    part6: null,
  },
  zho: {
    nativeName: '中文',
    nativeNameVariant: 'Zhōngwén, 汉语, 漢語',
    referenceName: 'Chinese',
    part1: 'zh',
    part2t: 'zho',
    part2b: 'chi',
    part6: null,
  },
  hrv: {
    nativeName: 'hrvatski jezik',
    referenceName: 'Croatian',
    part1: 'hr',
    part2t: 'hrv',
    part2b: 'hrv',
    part6: null,
  },
  ces: {
    nativeName: 'čeština',
    nativeNameVariant: 'český jazyk',
    referenceName: 'Czech',
    part1: 'cs',
    part2t: 'ces',
    part2b: 'cze',
    part6: null,
  },
  dan: {
    nativeName: 'dansk',
    referenceName: 'Danish',
    part1: 'da',
    part2t: 'dan',
    part2b: 'dan',
    part6: null,
  },
  nld: {
    nativeName: 'Nederlands',
    nativeNameVariant: 'Vlaams',
    referenceName: 'Dutch',
    part1: 'nl',
    part2t: 'nld',
    part2b: 'dut',
    part6: null,
  },
  eng: {
    nativeName: 'English',
    referenceName: 'English',
    part1: 'en',
    part2t: 'eng',
    part2b: 'eng',
    part6: 'engs',
  },
  epo: {
    nativeName: 'Esperanto',
    referenceName: 'Esperanto',
    part1: 'eo',
    part2t: 'epo',
    part2b: 'epo',
    part6: null,
  },
  est: {
    nativeName: 'eesti',
    nativeNameVariant: 'eesti keel',
    referenceName: 'Estonian',
    part1: 'et',
    part2t: 'est',
    part2b: 'est',
    part6: null,
  },
  fin: {
    nativeName: 'suomi',
    nativeNameVariant: 'suomen kieli',
    referenceName: 'Finnish',
    part1: 'fi',
    part2t: 'fin',
    part2b: 'fin',
    part6: null,
  },
  fra: {
    nativeName: 'français',
    nativeNameVariant: 'langue française',
    referenceName: 'French',
    part1: 'fr',
    part2t: 'fra',
    part2b: 'fre',
    part6: 'fras',
  },
  glg: {
    nativeName: 'galego',
    referenceName: 'Galician',
    part1: 'gl',
    part2t: 'glg',
    part2b: 'glg',
    part6: null,
  },
  kat: {
    nativeName: 'ქართული',
    referenceName: 'Georgian',
    part1: 'ka',
    part2t: 'kat',
    part2b: 'geo',
    part6: null,
  },
  deu: {
    nativeName: 'Deutsch',
    referenceName: 'German',
    part1: 'de',
    part2t: 'deu',
    part2b: 'ger',
    part6: 'deus',
  },
  ell: {
    nativeName: 'ελληνικά',
    referenceName: 'Greek',
    part1: 'el',
    part2t: 'ell',
    part2b: 'gre',
    part6: 'ells',
  },
  guj: {
    nativeName: 'ગુજરાતી',
    referenceName: 'Gujarati',
    part1: 'gu',
    part2t: 'guj',
    part2b: 'guj',
    part6: null,
  },
  heb: {
    nativeName: 'עברית',
    referenceName: 'Hebrew',
    part1: 'he',
    part2t: 'heb',
    part2b: 'heb',
    part6: null,
  },
  hin: {
    nativeName: 'हिन्दी',
    nativeNameVariant: 'हिंदी',
    referenceName: 'Hindi',
    part1: 'hi',
    part2t: 'hin',
    part2b: 'hin',
    part6: 'hins',
  },
  hun: {
    nativeName: 'magyar',
    referenceName: 'Hungarian',
    part1: 'hu',
    part2t: 'hun',
    part2b: 'hun',
    part6: null,
  },
  ind: {
    nativeName: 'Bahasa Indonesia',
    referenceName: 'Indonesian',
    part1: 'id',
    part2t: 'ind',
    part2b: 'ind',
    part6: null,
  },
  gle: {
    nativeName: 'Gaeilge',
    referenceName: 'Irish',
    part1: 'ga',
    part2t: 'gle',
    part2b: 'gle',
    part6: null,
  },
  isl: {
    nativeName: 'Íslenska',
    referenceName: 'Icelandic',
    part1: 'is',
    part2t: 'isl',
    part2b: 'ice',
    part6: null,
  },
  ita: {
    nativeName: 'italiano',
    referenceName: 'Italian',
    part1: 'it',
    part2t: 'ita',
    part2b: 'ita',
    part6: 'itas',
  },
  jpn: {
    nativeName: '日本語',
    referenceName: 'Japanese',
    part1: 'ja',
    part2t: 'jpn',
    part2b: 'jpn',
    part6: null,
  },
  kan: {
    nativeName: 'ಕನ್ನಡ',
    referenceName: 'Kannada',
    part1: 'kn',
    part2t: 'kan',
    part2b: 'kan',
    part6: null,
  },
  kaz: {
    nativeName: 'қазақ тілі',
    referenceName: 'Kazakh',
    part1: 'kk',
    part2t: 'kaz',
    part2b: 'kaz',
    part6: null,
  },
  kir: {
    nativeName: 'Кыргызча',
    nativeNameVariant: 'Кыргыз тили',
    referenceName: 'Kyrgyz',
    part1: 'ky',
    part2t: 'kir',
    part2b: 'kir',
    part6: null,
  },
  kor: {
    nativeName: '한국어',
    nativeNameVariant: '조선어',
    referenceName: 'Korean',
    part1: 'ko',
    part2t: 'kor',
    part2b: 'kor',
    part6: null,
  },
  lao: {
    nativeName: 'ພາສາລາວ',
    referenceName: 'Lao',
    part1: 'lo',
    part2t: 'lao',
    part2b: 'lao',
    part6: null,
  },
  lit: {
    nativeName: 'lietuvių kalba',
    referenceName: 'Lithuanian',
    part1: 'lt',
    part2t: 'lit',
    part2b: 'lit',
    part6: null,
  },
  lav: {
    nativeName: 'latviešu valoda',
    referenceName: 'Latvian',
    part1: 'lv',
    part2t: 'lav',
    part2b: 'lav',
    part6: null,
  },
  mkd: {
    nativeName: 'македонски јазик',
    referenceName: 'Macedonian',
    part1: 'mk',
    part2t: 'mkd',
    part2b: 'mac',
    part6: null,
  },
  msa: {
    nativeName: 'bahasa Melayu',
    nativeNameVariant: 'بهاس ملايو',
    referenceName: 'Malay',
    part1: 'ms',
    part2t: 'msa',
    part2b: 'may',
    part6: null,
  },
  mal: {
    nativeName: 'മലയാളം',
    referenceName: 'Malayalam',
    part1: 'ml',
    part2t: 'mal',
    part2b: 'mal',
    part6: null,
  },
  mar: {
    nativeName: 'मराठी',
    referenceName: 'Marathi',
    part1: 'mr',
    part2t: 'mar',
    part2b: 'mar',
    part6: null,
  },
  mon: {
    nativeName: 'Монгол хэл',
    referenceName: 'Mongolian',
    part1: 'mn',
    part2t: 'mon',
    part2b: 'mon',
    part6: null,
  },
  nep: {
    nativeName: 'नेपाली',
    referenceName: 'Nepali',
    part1: 'ne',
    part2t: 'nep',
    part2b: 'nep',
    part6: null,
  },
  nob: {
    nativeName: 'Norsk bokmål',
    referenceName: 'Norwegian Bokmål',
    part1: 'nb',
    part2t: 'nob',
    part2b: 'nob',
    part6: null,
  },
  nor: {
    nativeName: 'Norsk',
    referenceName: 'Norwegian',
    part1: 'no',
    part2t: 'nor',
    part2b: 'nor',
    part6: null,
  },
  ori: {
    nativeName: 'ଓଡ଼ିଆ',
    referenceName: 'Odia',
    part1: 'or',
    part2t: 'ori',
    part2b: 'ori',
    part6: null,
  },
  pan: {
    nativeName: 'ਪੰਜਾਬੀ',
    nativeNameVariant: 'پنجابی',
    referenceName: 'Punjabi',
    part1: 'pa',
    part2t: 'pan',
    part2b: 'pan',
    part6: null,
  },
  fas: {
    nativeName: 'فارسی',
    referenceName: 'Persian',
    part1: 'fa',
    part2t: 'fas',
    part2b: 'per',
    part6: null,
  },
  pol: {
    nativeName: 'język polski',
    nativeNameVariant: 'polszczyzna',
    referenceName: 'Polish',
    part1: 'pl',
    part2t: 'pol',
    part2b: 'pol',
    part6: 'pols',
  },
  pus: {
    nativeName: 'پښتو',
    referenceName: 'Pashto',
    part1: 'ps',
    part2t: 'pus',
    part2b: 'pus',
    part6: null,
  },
  por: {
    nativeName: 'português',
    referenceName: 'Portuguese',
    part1: 'pt',
    part2t: 'por',
    part2b: 'por',
    part6: null,
  },
  ron: {
    nativeName: 'limba română',
    referenceName: 'Romanian',
    part1: 'ro',
    part2t: 'ron',
    part2b: 'rum',
    part6: null,
  },
  rus: {
    nativeName: 'Русский',
    referenceName: 'Russian',
    part1: 'ru',
    part2t: 'rus',
    part2b: 'rus',
    part6: null,
  },
  srp: {
    nativeName: 'српски језик',
    referenceName: 'Serbian',
    part1: 'sr',
    part2t: 'srp',
    part2b: 'srp',
    part6: null,
  },
  sin: {
    nativeName: 'සිංහල',
    referenceName: 'Sinhala',
    part1: 'si',
    part2t: 'sin',
    part2b: 'sin',
    part6: null,
  },
  slk: {
    nativeName: 'slovenčina',
    nativeNameVariant: 'slovenský jazyk',
    referenceName: 'Slovak',
    part1: 'sk',
    part2t: 'slk',
    part2b: 'slo',
    part6: null,
  },
  slv: {
    nativeName: 'slovenščina',
    nativeNameVariant: 'slovenski jezik',
    referenceName: 'Slovenian',
    part1: 'sl',
    part2t: 'slv',
    part2b: 'slv',
    part6: null,
  },
  spa: {
    nativeName: 'español',
    referenceName: 'Spanish',
    part1: 'es',
    part2t: 'spa',
    part2b: 'spa',
    part6: null,
  },
  swa: {
    nativeName: 'Kiswahili',
    referenceName: 'Swahili',
    part1: 'sw',
    part2t: 'swa',
    part2b: 'swa',
    part6: null,
  },
  swe: {
    nativeName: 'svenska',
    referenceName: 'Swedish',
    part1: 'sv',
    part2t: 'swe',
    part2b: 'swe',
    part6: null,
  },
  tam: {
    nativeName: 'தமிழ்',
    referenceName: 'Tamil',
    part1: 'ta',
    part2t: 'tam',
    part2b: 'tam',
    part6: null,
  },
  tel: {
    nativeName: 'తెలుగు',
    referenceName: 'Telugu',
    part1: 'te',
    part2t: 'tel',
    part2b: 'tel',
    part6: null,
  },
  tha: {
    nativeName: 'ไทย',
    referenceName: 'Thai',
    part1: 'th',
    part2t: 'tha',
    part2b: 'tha',
    part6: null,
  },
  tgl: {
    nativeName: 'Wikang Tagalog',
    nativeNameVariant: 'ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔',
    referenceName: 'Tagalog',
    part1: 'tl',
    part2t: 'tgl',
    part2b: 'tgl',
    part6: null,
  },
  tur: {
    nativeName: 'Türkçe',
    referenceName: 'Turkish',
    part1: 'tr',
    part2t: 'tur',
    part2b: 'tur',
    part6: null,
  },
  ukr: {
    nativeName: 'українська мова',
    referenceName: 'Ukrainian',
    part1: 'uk',
    part2t: 'ukr',
    part2b: 'ukr',
    part6: null,
  },
  urd: {
    nativeName: 'اردو',
    referenceName: 'Urdu',
    part1: 'ur',
    part2t: 'urd',
    part2b: 'urd',
    part6: null,
  },
  uzb: {
    nativeName: 'Oʻzbek',
    nativeNameVariant: 'Ўзбек, أۇزبېك',
    referenceName: 'Uzbek',
    part1: 'uz',
    part2t: 'uzb',
    part2b: 'uzb',
    part6: null,
  },
  vie: {
    nativeName: 'Tiếng Việt',
    referenceName: 'Vietnamese',
    part1: 'vi',
    part2t: 'vie',
    part2b: 'vie',
    part6: null,
  },
  cym: {
    nativeName: 'Cymraeg',
    referenceName: 'Welsh',
    part1: 'cy',
    part2t: 'cym',
    part2b: 'wel',
    part6: null,
  },
  zul: {
    nativeName: 'isiZulu',
    referenceName: 'Zulu',
    part1: 'zu',
    part2t: 'zul',
    part2b: 'zul',
    part6: null,
  },
}

export const map2to3: Record<string, string> = {
  aa: 'aar',
  ab: 'abk',
  af: 'afr',
  ak: 'aka',
  am: 'amh',
  ar: 'ara',
  an: 'arg',
  as: 'asm',
  av: 'ava',
  ae: 'ave',
  ay: 'aym',
  az: 'aze',
  ba: 'bak',
  bm: 'bam',
  be: 'bel',
  bn: 'ben',
  bi: 'bis',
  bo: 'bod',
  bs: 'bos',
  br: 'bre',
  bg: 'bul',
  ca: 'cat',
  cs: 'ces',
  ch: 'cha',
  ce: 'che',
  cu: 'chu',
  cv: 'chv',
  kw: 'cor',
  co: 'cos',
  cr: 'cre',
  cy: 'cym',
  da: 'dan',
  de: 'deu',
  dv: 'div',
  dz: 'dzo',
  el: 'ell',
  en: 'eng',
  eo: 'epo',
  et: 'est',
  eu: 'eus',
  ee: 'ewe',
  fo: 'fao',
  fa: 'fas',
  fj: 'fij',
  fi: 'fin',
  fr: 'fra',
  fy: 'fry',
  ff: 'ful',
  gd: 'gla',
  ga: 'gle',
  gl: 'glg',
  gv: 'glv',
  gn: 'grn',
  gu: 'guj',
  ht: 'hat',
  ha: 'hau',
  sh: 'hbs',
  he: 'heb',
  hz: 'her',
  hi: 'hin',
  ho: 'hmo',
  hr: 'hrv',
  hu: 'hun',
  hy: 'hye',
  ig: 'ibo',
  io: 'ido',
  ii: 'iii',
  iu: 'iku',
  ie: 'ile',
  ia: 'ina',
  id: 'ind',
  ik: 'ipk',
  is: 'isl',
  it: 'ita',
  jv: 'jav',
  ja: 'jpn',
  kl: 'kal',
  kn: 'kan',
  ks: 'kas',
  ka: 'kat',
  kr: 'kau',
  kk: 'kaz',
  km: 'khm',
  ki: 'kik',
  rw: 'kin',
  ky: 'kir',
  kv: 'kom',
  kg: 'kon',
  ko: 'kor',
  kj: 'kua',
  ku: 'kur',
  lo: 'lao',
  la: 'lat',
  lv: 'lav',
  li: 'lim',
  ln: 'lin',
  lt: 'lit',
  lb: 'ltz',
  lu: 'lub',
  lg: 'lug',
  mh: 'mah',
  ml: 'mal',
  mr: 'mar',
  mk: 'mkd',
  mg: 'mlg',
  mt: 'mlt',
  mn: 'mon',
  mi: 'mri',
  ms: 'msa',
  my: 'mya',
  na: 'nau',
  nv: 'nav',
  nr: 'nbl',
  nd: 'nde',
  ng: 'ndo',
  ne: 'nep',
  nl: 'nld',
  nn: 'nno',
  nb: 'nob',
  no: 'nor',
  ny: 'nya',
  oc: 'oci',
  oj: 'oji',
  or: 'ori',
  om: 'orm',
  os: 'oss',
  pa: 'pan',
  pi: 'pli',
  pl: 'pol',
  pt: 'por',
  ps: 'pus',
  qu: 'que',
  rm: 'roh',
  ro: 'ron',
  rn: 'run',
  ru: 'rus',
  sg: 'sag',
  sa: 'san',
  si: 'sin',
  sk: 'slk',
  sl: 'slv',
  se: 'sme',
  sm: 'smo',
  sn: 'sna',
  sd: 'snd',
  so: 'som',
  st: 'sot',
  es: 'spa',
  sq: 'sqi',
  sc: 'srd',
  sr: 'srp',
  ss: 'ssw',
  su: 'sun',
  sw: 'swa',
  sv: 'swe',
  ty: 'tah',
  ta: 'tam',
  tt: 'tat',
  te: 'tel',
  tg: 'tgk',
  tl: 'tgl',
  th: 'tha',
  ti: 'tir',
  to: 'ton',
  tn: 'tsn',
  ts: 'tso',
  tk: 'tuk',
  tr: 'tur',
  tw: 'twi',
  ug: 'uig',
  uk: 'ukr',
  ur: 'urd',
  uz: 'uzb',
  ve: 'ven',
  vi: 'vie',
  vo: 'vol',
  wa: 'wln',
  wo: 'wol',
  xh: 'xho',
  yi: 'yid',
  yo: 'yor',
  za: 'zha',
  zh: 'zho',
  zu: 'zul',
}

export const map3to2: Record<string, string> = {
  aar: 'aa',
  abk: 'ab',
  afr: 'af',
  aka: 'ak',
  amh: 'am',
  ara: 'ar',
  arg: 'an',
  asm: 'as',
  ava: 'av',
  ave: 'ae',
  aym: 'ay',
  aze: 'az',
  bak: 'ba',
  bam: 'bm',
  bel: 'be',
  ben: 'bn',
  bis: 'bi',
  bod: 'bo',
  bos: 'bs',
  bre: 'br',
  bul: 'bg',
  cat: 'ca',
  ces: 'cs',
  cha: 'ch',
  che: 'ce',
  chu: 'cu',
  chv: 'cv',
  cor: 'kw',
  cos: 'co',
  cre: 'cr',
  cym: 'cy',
  dan: 'da',
  deu: 'de',
  div: 'dv',
  dzo: 'dz',
  ell: 'el',
  eng: 'en',
  epo: 'eo',
  est: 'et',
  eus: 'eu',
  ewe: 'ee',
  fao: 'fo',
  fas: 'fa',
  fij: 'fj',
  fin: 'fi',
  fra: 'fr',
  fry: 'fy',
  ful: 'ff',
  gla: 'gd',
  gle: 'ga',
  glg: 'gl',
  glv: 'gv',
  grn: 'gn',
  guj: 'gu',
  hat: 'ht',
  hau: 'ha',
  hbs: 'sh',
  heb: 'he',
  her: 'hz',
  hin: 'hi',
  hmo: 'ho',
  hrv: 'hr',
  hun: 'hu',
  hye: 'hy',
  ibo: 'ig',
  ido: 'io',
  iii: 'ii',
  iku: 'iu',
  ile: 'ie',
  ina: 'ia',
  ind: 'id',
  ipk: 'ik',
  isl: 'is',
  ita: 'it',
  jav: 'jv',
  jpn: 'ja',
  kal: 'kl',
  kan: 'kn',
  kas: 'ks',
  kat: 'ka',
  kau: 'kr',
  kaz: 'kk',
  khm: 'km',
  kik: 'ki',
  kin: 'rw',
  kir: 'ky',
  kom: 'kv',
  kon: 'kg',
  kor: 'ko',
  kua: 'kj',
  kur: 'ku',
  lao: 'lo',
  lat: 'la',
  lav: 'lv',
  lim: 'li',
  lin: 'ln',
  lit: 'lt',
  ltz: 'lb',
  lub: 'lu',
  lug: 'lg',
  mah: 'mh',
  mal: 'ml',
  mar: 'mr',
  mkd: 'mk',
  mlg: 'mg',
  mlt: 'mt',
  mon: 'mn',
  mri: 'mi',
  msa: 'ms',
  mya: 'my',
  nau: 'na',
  nav: 'nv',
  nbl: 'nr',
  nde: 'nd',
  ndo: 'ng',
  nep: 'ne',
  nld: 'nl',
  nno: 'nn',
  nob: 'nb',
  nor: 'no',
  nya: 'ny',
  oci: 'oc',
  oji: 'oj',
  ori: 'or',
  orm: 'om',
  oss: 'os',
  pan: 'pa',
  pli: 'pi',
  pol: 'pl',
  por: 'pt',
  pus: 'ps',
  que: 'qu',
  roh: 'rm',
  ron: 'ro',
  run: 'rn',
  rus: 'ru',
  sag: 'sg',
  san: 'sa',
  sin: 'si',
  slk: 'sk',
  slv: 'sl',
  sme: 'se',
  smo: 'sm',
  sna: 'sn',
  snd: 'sd',
  som: 'so',
  sot: 'st',
  spa: 'es',
  sqi: 'sq',
  srd: 'sc',
  srp: 'sr',
  ssw: 'ss',
  sun: 'su',
  swa: 'sw',
  swe: 'sv',
  tah: 'ty',
  tam: 'ta',
  tat: 'tt',
  tel: 'te',
  tgk: 'tg',
  tgl: 'tl',
  tha: 'th',
  tir: 'ti',
  ton: 'to',
  tsn: 'tn',
  tso: 'ts',
  tuk: 'tk',
  tur: 'tr',
  twi: 'tw',
  uig: 'ug',
  ukr: 'uk',
  urd: 'ur',
  uzb: 'uz',
  ven: 've',
  vie: 'vi',
  vol: 'vo',
  wln: 'wa',
  wol: 'wo',
  xho: 'xh',
  yid: 'yi',
  yor: 'yo',
  zha: 'za',
  zho: 'zh',
  zul: 'zu',
}
